[phases.setup]
cmds = [
  "apt-get update && apt-get install -y --no-install-recommends glibc-source libc-bin curl wget"
]

[phases.build]
cmds = [
  "nix-env -if .nixpacks/nixpkgs-5624e1334b26ddc18da37e132b6fa8e93b481468.nix && nix-collect-garbage -d"
]

[phases.start]
cmds = [
  "node ./dist/server/entry.mjs"
]